name: "AnyiLive"
author: "AnyiLive"
highlighter: rouge
permalink: /:year/:month/:day/:title

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html

