name: "AnyiLive"
author: "AnyiLive"
highlighter: rouge
permalink: /:year/:month/:day/:title
paginate: 50
paginate_path: /blog/page:num/

navigations:
  - title: About
    icon: 👤
    href: /about.html

